# ***Broadcasting & Vectorization***

- NumPy broadcasting expands the smaller array into the same size of greater array during the arithmetic operation
- why use numpy broadcasting?
  - Avoid manual reshaping
  - Avoid memory duplication
  - Makes the code simple and smooth to understand


In [19]:
# import numpy as np

# # arr = np.array([[1,2,3,4], [5,6,7,8]])

# # print(arr)

# # newArr = arr * 5   # [1 2 3 4] [5 6 7 8] + [5 5 5 5] [5 5 5 5]  ---> [6 7 8 9 10]
# # print(newArr)


# arr1 = np.array([[1,2,3,4], [6,7,8,9]])
# print(f"first array - \n {arr1}\n\n")

# arr2 = np.array([10,20,30, 40,50])
# print(f"second array - \n {arr2}\n\n")

# newArr = arr1 * arr2
# print(f"new array after broadcasting - \n {newArr}")

first array - 
 [[1 2 3 4]
 [6 7 8 9]]


second array - 
 [10 20 30 40 50]




ValueError: operands could not be broadcast together with shapes (2,4) (5,) 

# ***Vectorization in NumPy***

- Performing operations on entire array at once without using Python loops

- Why use Vectorization in NumPy?
    - Eliminates python loops
    - Uses optimized C-Level inplementation
    - Much Faster as compared to python loops
    - easy to understand code (cleaner code)
    - Increases the Readability of the code

In [26]:
import time as tl

# startTime = tl.time()
# li = [14,15,16,78]
# newli = []
# newLi = li + 5    # [14,15,16,78] + [5, 5 ,5 , 5] --> it wil not gonna apply broadcasting as well as vectorization on python list
# print(newLi)
# through this we can't operate the li with adding 5 to entire python list
# to operate the above operation in python we have to use python loops
# for num in li:
#   newli.append(num + 5)
# endTime = tl.time()

startTime = tl.time()
li = []
newLi = []
for num in range(1, 10000000):
  li.append(num)

for num in li:
  newLi.append(num + 5)

endTime = tl.time()

# print(li)
# print(newLi)
# print(newli)
print(endTime - startTime)

2.3876125812530518


In [27]:
import numpy as np
import time as tl
start_time = tl.time()
arr = np.arange(1, 10000000)

newArr = arr + 5
end_time = tl.time()
# print(arr)
# print(newArr)
print(end_time - start_time)

0.13024187088012695


# ***Random methods in NumPy***
it will help us generate an random array through a given range


*   np.random.rand()
*   np.random.randn()



In [79]:
import numpy as np

# randomArr = np.random.rand()*20
# randomArr = np.random.rand(6)*20
# randomArr = np.random.rand(2,6, 3)*20
# print(randomArr)

# randomArr = np.random.randn()
# randomArr = np.random.randn()*50   # now, here the range is -50 to 50 not 0 to 50
# print(randomArr)
# randomArr = np.random.randn(3)*50   # now, here the range is -150 to 150 not 0 to 50
# print(randomArr)
# randomArr = np.random.randn(3, 4)*70
# print(randomArr)


# randomArr = np.random.randint(20, 90, size=[4,5])
# print(randomArr)


[[39 81 79 81 25]
 [56 58 25 41 33]
 [81 42 49 33 26]
 [33 32 80 41 76]]
