# ***More Methods to create an NumPy Array***

1. np.zeros()
2. np.ones()
3. np.full()

In [12]:
import numpy as np

# zeroArr = np.zeros([2], dtype=np.int64)  # 1D-Array
# zeroArr = np.zeros([2,3], dtype=np.int64)  # 2D-Array
# zeroArr = np.zeros([3,2,4], dtype=np.int64)  # 3D-Array
# print(zeroArr)

# onesArr = np.ones([3])    # 1D-Array
# onesArr = np.ones([3, 4], dtype=np.int64)    # 2D-Array
# onesArr = np.ones([3, 2, 2], dtype=np.int64)    # 3D-Array
# print(onesArr)

# fullArr = np.full([3], 5)    # 1D-Array
# fullArr = np.full([3, 4], 7)    # 2D-Array
# fullArr = np.full([3, 2, 2], 9)    # 3D-Array
# print(fullArr)



[[[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[[9 9]
  [9 9]]

 [[9 9]
  [9 9]]

 [[9 9]
  [9 9]]]


# **Slicing in NumPy**

In [45]:
arr = np.arange(1, 37)
# print(arr, '\n')
# slicing in 1D array - arrayName[start:end:skip]
# newArr = arr[9:15]
# print(newArr)

# newArr = arr[9:25:2]
# print(newArr)

# newArr = arr[:]
# newArr[0] = 85
# print(newArr)
# print(arr)

# newArr = arr[::-1]
# print(newArr)



# 2D-slicing in NumPy -
arr2D = arr.reshape(6,6)
# print(arr2D, '\n')
# arr2D = arr.reshape(9,4)
# arr2D = arr.reshape(12,3)

# newArr2D = arr2D[:, :]
# print(newArr2D)

# newArr2D = arr2D[0:3, 0:3]
# print(newArr2D)

# newArr2D = arr2D[3:, 2:5]
# print(newArr2D)

# newArr2D = arr2D[3:, 4:1:-1]
# print(newArr2D)

# newArr2D = arr2D[2:5, 1:4]
# print(newArr2D)

# newArr2D = arr2D[1:, 3:]
# print(newArr2D)



# slicing in 3D array - arrayNAme[start:end:skip, start:end:skip, start:end:skip]
# arr3D = arr.reshape(3,4,3)
# print(arr3D, '\n')
# new3Darr = arr3D[0, 2:, :]
# print(new3Darr, '\n')
# new3Darr = arr3D[0:2, 1:3, :2]
# print(new3Darr, '\n')

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]] 

[[ 7  8  9]
 [10 11 12]] 

[[[ 4  5]
  [ 7  8]]

 [[16 17]
  [19 20]]] 

