# ***Flattening Array in NumPy***

In [ ]:
# import numpy as np

# arr = np.arange(1, 37)

# _2DArray = arr.reshape(6,6)
# _3DArray = arr.reshape(3,3,4)

# print(f"2D Array - {_2DArray}")
# print(_2DArray, " \n \n")
# print(f"3D Array - {_3DArray}")

# Flatten method - used to flatten an 2D or 3D array -
# flat2DArrUsingFlatten = _2DArray.flatten()
# print(f"flatten 2D Array - {flat2DArrUsingFlatten} \n \n")

# flat3DArr = _3DArray.flatten()
# print(f"flatten 3D Array - {flat3DArr}")


# Ravel Method - used to flatten an 2D or 3D array -
# flat2DArrUsingRavel = _2DArray.ravel()
# print(f"Ravel 2D Array - {flat2DArrUsingRavel}")

# flat3DArr = _3DArray.ravel()
# print(f"Ravel 3D Array - {flat3DArr}")

# flat2DArrUsingRavel[0] = 66
# print(_2DArray)
# print(flat2DArrUsingRavel)

# flat2DArrUsingFlatten[0] = 45
# print(_2DArray)
# print(flat2DArrUsingFlatten)

# flatten method will make a flatten array by making a shallow copy of the array which is converted into a flatten array
# ravel method will also make a flatten array by making a deep copy of the array which is converted into a flatten array

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]  
 

flatten 2D Array - [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36] 
 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[45  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


# ***Fancy Indexing in NumPy***

In [4]:
import numpy as np
# fancy indexing (+ve)
# arr = np.array([1,2,3,4,5,6])
# print(arr)

# newArr = arr[[1,3,5]]
# print(newArr)


# # fancy indexing (-ve)
# negIndArr = arr[[-1, -3, -5]]
# print(negIndArr)


# 3D Array - fancy indexing
# arr = np.arange(1, 28).reshape(3,3,3)
# print(arr, '\n \n')

# newArr = arr[[1], [0,1,2], [2,2,2]]
# print(newArr)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 
 

[12 15 18]


# ***Boolean Masking in NumPy***

In [ ]:
arr = np.arange(1, 41)
print(arr)

evenArr = arr[arr % 2 == 0]
print(evenArr)

oddArr = arr[arr%2 == 1]
print(oddArr)

# Corrected: Use the bitwise '&' operator for element-wise logical AND
ArrGreaterThan18 = arr[(arr > 18) & (arr < 25)]
print(ArrGreaterThan18)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]
[19 20 21 22 23 24]


In [ ]:
# Demonstrate .any() and .all()

print("\n--- Demonstrating .any() and .all() ---")

# Check if ANY element in arr is greater than 30
is_any_greater_than_30 = (arr > 30).any()
print(f"Is any element in arr greater than 30? {is_any_greater_than_30}")

# Check if ALL elements in arr are greater than 0
is_all_greater_than_0 = (arr > 0).all()
print(f"Are all elements in arr greater than 0? {is_all_greater_than_0}")

# Check if ALL elements in arr are less than 20 (this should be False)
is_all_less_than_20 = (arr < 20).all()
print(f"Are all elements in arr less than 20? {is_all_less_than_20}")



--- Demonstrating .any() and .all() ---
Is any element in arr greater than 30? True
Are all elements in arr greater than 0? True
Are all elements in arr less than 20? False
