# ***Pre-Built Methods in NumPy for the Numerical Manipulation***

In [11]:
import numpy as np

arr = np.array([[1,2,3], [5,6, 7]])
# arr = np.array([[1,2, 3], [5,6]])   # it will cause an inhomogeneous shape error (ValueError) because the number of columns must be same in every list
print(arr)
print(np.ndim(arr))  # it will return the dimension of the array (1D | 2D | 3D)
print(np.shape(arr)) # it will return the no. of rows and columns (m,n)
print(np.size(arr))  # it will return the count of the elements present in an array

[[1 2 3]
 [5 6 7]]
2
(2, 3)
6


# ***Type Conversion in NumPy***

In [16]:
# let us say we have a stringular array -
strArr = np.array(['10', '20', '30', '40'])
print(strArr)
print(strArr.dtype)
# converting stringular array into int array
intArr = np.array(strArr, dtype = np.int64)
print(intArr)
print(intArr.dtype)

# converting stringular array into float array
intArr = np.array(strArr, dtype = np.float64)
print(intArr)
print(intArr.dtype)

['10' '20' '30' '40']
<U2
[10. 20. 30. 40.]
float64


In [21]:
# np.arange(startRange, endRange, skipValue) - it will make a array of the provided range

rangedArr = np.arange(20, 0, -2)
print(rangedArr)

[20 18 16 14 12 10  8  6  4  2]


In [31]:
# np.linspace(startPoint, endPoint, divisions)
eqDivArr = np.linspace(0, 20, 10, dtype=np.int64)
print(eqDivArr)
print(np.size(eqDivArr))


[ 0  2  4  6  8 11 13 15 17 20]
10


In [50]:
# np.reshape([m,n], array) -
# one-dimension array
_1D_Arr = np.arange(25, 41)
# print(_1D_Arr)
# print(np.shape(_1D_Arr))
# print(np.size(_1D_Arr))

# two-dimension array
# _2D_Arr1 = _1D_Arr.reshape([2,8])
# print(_2D_Arr1)
# print(np.ndim(_2D_Arr1))
# print(np.shape(_2D_Arr1))
# print(np.size(_2D_Arr1))

# _2D_Arr2 = _1D_Arr.reshape([4,4])
# print(_2D_Arr2)
# print(np.ndim(_2D_Arr2))
# print(np.shape(_2D_Arr2))
# print(np.size(_2D_Arr2))


# Three-Dimension Array -
_3DArr1 = _1D_Arr.reshape(2,2,4)
print(_3DArr1)
_3DArr2 = _1D_Arr.reshape(2,4,2)
print(_3DArr2)
_3DArr3 = _1D_Arr.reshape(4,2,2)
print(_3DArr3)
_3DArr4 = _1D_Arr.reshape(1,4,4)
print(_3DArr4)
_3DArr5 = _1D_Arr.reshape(4,1,4)
print(_3DArr5)
_3DArr6 = _1D_Arr.reshape(4,4,1)
print(_3DArr6)

[[[25 26 27 28]
  [29 30 31 32]]

 [[33 34 35 36]
  [37 38 39 40]]]
[[[25 26]
  [27 28]
  [29 30]
  [31 32]]

 [[33 34]
  [35 36]
  [37 38]
  [39 40]]]
[[[25 26]
  [27 28]]

 [[29 30]
  [31 32]]

 [[33 34]
  [35 36]]

 [[37 38]
  [39 40]]]
[[[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]
  [37 38 39 40]]]
[[[25 26 27 28]]

 [[29 30 31 32]]

 [[33 34 35 36]]

 [[37 38 39 40]]]
[[[25]
  [26]
  [27]
  [28]]

 [[29]
  [30]
  [31]
  [32]]

 [[33]
  [34]
  [35]
  [36]]

 [[37]
  [38]
  [39]
  [40]]]
